<Project>
  <PropertyGroup>
    <ValheimDir Condition="'$(ValheimDir)' == ''">$(MSBuildProgramFiles32)/Steam/steamapps/common/Valheim</ValheimDir>
  </PropertyGroup>
  <Target Name="CheckValheimInstallation" BeforeTargets="ResolveReferences">
    <Error Condition="!Exists('$(ValheimDir)/Valheim_Data/Managed/Newtonsoft.Json.dll')" Text="Set ValheimDir to your Valheim installation path (environment variable or -p:ValheimDir=...)." />
  </Target>
</Project>
