using System;
using System.Linq;
using System.Text.Json;
using ValheimMMOMOD;

class Program
{
    static int checks;
    static void Check(bool value, string name) { if (!value) throw new Exception(name); checks++; Console.WriteLine("PASS " + name); }
    static void Main()
    {
        var now = new DateTime(2026, 9, 19, 12, 0, 0, DateTimeKind.Utc);
        var s = new GameService(new WorldStore()); var a = s.Join("a", "A", 1000, now); var b = s.Join("b", "B", 10, now); var c = s.Join("c", "C", 0, now);
        string Run(string who, string action, string target = "", string text = "", int amount = 0, string id = "test") => s.Execute(who, new Command { action = action, target = target, text = text, amount = amount, id = id }, now);
        Run("a", "transfer", "b", amount: 300); Check(a.gold == 700 && b.gold == 310, "Transfer debits and credits exactly once per execution");
        Run("a", "transfer", "missing", amount: 50); Check(a.gold == 700, "Unknown recipient does not debit gold");
        Run("a", "transfer", "a", amount: 50); Check(a.gold == 700, "Self transfer rejected");
        Run("a", "transfer", "b", amount: -10); Check(a.gold == 700 && b.gold == 310, "Negative transfer rejected");
        Run("a", "transfer", "b", amount: 701); Check(a.gold == 700, "Overdraft rejected");
        Run("a", "createGuild", text: "Ravens"); Check(a.guild != "" && a.role == "Capogilda", "Guild founder is leader");
        Run("a", "inviteGuild", "b"); Check(b.guild == "" && b.invitations.Contains(a.guild), "Guild invitation requires acceptance");
        Run("c", "acceptGuild", a.guild); Check(c.guild == "", "Uninvited player cannot join");
        Run("b", "acceptGuild", a.guild); Check(b.guild == a.guild && b.role == "Membro", "Invited player can join");
        Run("b", "inviteGuild", "c"); Check(c.invitations.Count == 0, "Ordinary member cannot invite");
        Run("b", "promote", "b"); Check(b.role == "Membro", "Role escalation rejected");
        Run("a", "promote", "b"); Run("b", "inviteGuild", "c"); Check(b.role == "Ufficiale" && c.invitations.Count == 1, "Officer can invite");
        s.MaxMembers = 2; Run("c", "acceptGuild", a.guild); Check(c.guild == "", "Member cap checked on acceptance"); s.MaxMembers = 20;
        Run("a", "tag", text: "RAV"); Check(s.Guild(a).tag == "RAV", "Leader can set guild tag");
        Run("b", "tag", text: "BAD"); Check(s.Guild(a).tag == "RAV", "Officer cannot change leader settings");
        string guild = a.guild; Run("a", "leaveGuild"); Check(a.guild == "" && b.role == "Capogilda", "Leader exit promotes successor");
        Run("b", "leaveGuild"); Check(s.Data.guilds.Count == 0 && c.invitations.Count == 0, "Empty guild and stale invitations removed");
        Run("a", "friendRequest", "b"); Check(b.requests.Contains("a") && !a.friends.Contains("b"), "Friend request awaits consent");
        Run("b", "friendAccept", "a"); Check(a.friends.Contains("b") && b.friends.Contains("a"), "Friend acceptance is reciprocal");
        Run("a", "block", "b"); Run("b", "friendRequest", "a"); Check(!a.friends.Contains("b") && !b.friends.Contains("a") && a.requests.Count == 0, "Block removes friendship and prevents new request");
        Run("a", "unblock", "b"); Run("b", "friendRequest", "a"); Check(a.requests.Contains("b"), "Unblock permits requests");
        var daily = a.quests.First(q => q.period == "Giornaliera"); int before = a.gold;
        Run("a", "claim", daily.id); Check(a.gold == before && !daily.claimed, "Incomplete mission cannot be claimed");
        Run("a", "progress", text: daily.type, amount: daily.target);
        while (daily.progress < daily.target) Run("a", "progress", text: daily.type, amount: 1);
        before = a.gold; Run("a", "claim", daily.id); Run("a", "claim", daily.id); Check(a.gold == before + daily.reward && daily.claimed, "Quest reward cannot be claimed twice");
        s.EnsureQuests(a, now); Check(a.quests.Count(q => q.period == "Giornaliera" && !q.claimed) == 2, "Claimed daily is not regenerated the same day");
        s.EnsureQuests(a, now.AddDays(1)); Check(a.quests.Any(q => q.period == "Giornaliera" && !q.claimed), "New day generates new daily");
        Check(a.quests.Count(q => q.period == "Settimanale" && !q.claimed) == 3, "Three real weekly objectives exist");
        before = a.gold; Run("a", "withdraw", amount: 50, id: "w1"); Check(a.gold == before - 50 && a.grants.Count == 1, "Withdrawal reserves gold and creates delivery grant");
        Run("a", "withdrawAck", "w1", amount: 20); Check(a.gold == before - 20 && a.grants.Count == 0, "Partial delivery refunds undelivered coins");
        Run("a", "withdrawAck", "w1", amount: 0); Check(a.gold == before - 20, "Duplicate delivery acknowledgment does not refund twice");
        var restored = MMOJson.FromJson<WorldStore>(MMOJson.ToJson(s.Data));
        Check(restored.players.Find(p => p.id == "a").gold == a.gold && restored.players.Find(p => p.id == "a").quests.Any(q => q.claimed), "Persistent state retains balance and quest history");
        var wire = new Snapshot { self = a, guild = s.Guild(a), economy = true, quests = true };
        wire.people.Add(new PublicMember { id = "b", name = "B", online = true });
        var received = MMOJson.FromJson<Snapshot>(MMOJson.ToJson(wire));
        Check(received.self.id == "a" && received.economy && received.people.Single().online, "Wire snapshot round trip retains player and presence");
        var command = MMOJson.FromJson<Command>(MMOJson.ToJson(new Command { id = "unique", action = "transfer", target = "b", amount = 7 }));
        Check(command.id == "unique" && command.action == "transfer" && command.amount == 7, "Wire command round trip retains action and amount");
        s.Economy = false; before = a.gold; Run("a", "deposit", amount: 100); Run("a", "withdraw", amount: 1); Run("a", "transfer", "b", amount: 1);
        Check(a.gold == before, "Disabled economy rejects all balance operations"); s.Economy = true;
        b.gold = int.MaxValue; before = a.gold; Run("a", "transfer", "b", amount: 1); Check(a.gold == before && b.gold == int.MaxValue, "Overflow transfer rejected without debit");
        var qs = new GameService(null); var hero = qs.Join("hero", "Hero", 0, now);
        string QuestRun(string action, QuestRecord q, string type = "") => qs.Execute("hero", new Command { action = action, target = q.id, text = type }, now);
        Check(hero.quests.Count(q => q.period == "Giornaliera") == 3, "Three daily slots generated");
        var original = hero.quests.First(q => q.period == "Giornaliera"); original.progress = 1;
        string choice = original.type == "gather" ? "kill" : "gather";
        QuestRun("replaceQuest", original, choice);
        var changed = hero.quests.Single(q => q.id == original.id);
        Check(changed.type == choice && changed.progress == 0 && changed.target < (choice == "kill" ? 5 : 30) && hero.dailyChanges == 1, "Replacement is different, easier and resets only its progress");
        QuestRun("replaceQuest", changed, choice);
        Check(hero.dailyChanges == 1, "Same activity cannot consume a change");
        for (int i = 0; i < 2; i++) { choice = changed.type == "kill" ? "gather" : "kill"; QuestRun("replaceQuest", changed, choice); changed = hero.quests.Single(q => q.id == original.id); }
        QuestRun("replaceQuest", changed, changed.type == "kill" ? "gather" : "kill");
        Check(hero.dailyChanges == 3 && hero.quests.Contains(changed), "Only three replacements allowed per day");
        var weeklyQuest = hero.quests.First(q => q.period == "Settimanale"); QuestRun("replaceQuest", weeklyQuest, "level");
        Check(hero.quests.Contains(weeklyQuest), "Weekly quests cannot be replaced");
        Check(GameService.QuestXP("kill", 5) == 100 && GameService.QuestXP("gather", 30) == 60 && GameService.QuestXP("explore", 60) == 60 && GameService.QuestXP("level", 2) == 100, "XP reflects activity and target");
        changed.progress = changed.target; qs.Economy = false;
        QuestRun("claim", changed); QuestRun("claim", changed);
        Check(hero.xp == changed.xpReward && hero.gold == 0 && changed.claimed, "Personal XP claimed once without guild or economy");
        QuestRun("replaceQuest", changed, "level"); Check(hero.quests.Contains(changed), "Claimed quest cannot be replaced");
        var savedHero = MMOJson.FromJson<WorldStore>(MMOJson.ToJson(qs.Data)).players.Single();
        Check(savedHero.xp == hero.xp && savedHero.dailyChanges == 3 && savedHero.changeDay == hero.changeDay, "XP and daily replacement limits survive reload");
        qs.EnsureQuests(hero, now.AddDays(1));
        Check(hero.dailyChanges == 0 && hero.quests.Count(q => !q.claimed && q.period == "Giornaliera") == 3 && hero.xp == changed.xpReward, "Next day resets changes and missions while preserving XP");
        var legacy = new MemberRecord { id = "old", name = "Old" };
        legacy.quests.Add(new QuestRecord { id = "d:" + now.ToString("yyyy-MM-dd"), period = "Giornaliera", type = "kill", target = 5, progress = 3, reward = 100 });
        qs.EnsureQuests(legacy, now);
        Check(legacy.quests[0].progress == 3 && legacy.quests[0].xpReward == 100 && legacy.quests.Count(q => q.period == "Giornaliera") == 3, "Existing daily progress preserved when adding slots and XP");
        Check(GameService.PersonalLevel(0) == 1 && GameService.PersonalLevel(100) == 2 && GameService.PersonalLevel(400) == 3, "Personal level grows with accumulated XP");
        var shop = new GameService(null); var buyer = shop.Join("buyer", "Buyer", 500, now);
        string Buy(string item, string id, bool near = true, int amount = 0) => shop.Execute("buyer", new Command { action = "trade", target = item, id = id, amount = amount }, now, near);
        string Ack(string id, int amount) => shop.Execute("buyer", new Command { action = "tradeAck", target = id, amount = amount }, now);
        Buy("Wood", "remote", false); Check(buyer.gold == 500 && buyer.resourceGrants.Count == 0, "Distant player cannot purchase");
        Buy("SwordCheat", "invalid"); Check(buyer.gold == 500, "Unknown resource rejected without debit");
        Buy("Wood", "buy1", amount: -9000);
        Check(buyer.gold == 480 && buyer.resourceGrants.Single().amount == 10 && buyer.resourceGrants.Single().unitPrice == 2, "Server catalog controls purchase quantity and price");
        Buy("Wood", "buy1"); Buy("Stone", "buy2");
        Check(buyer.gold == 480 && buyer.resourceGrants.Count == 1, "Pending purchase blocks duplicate and concurrent deliveries");
        Ack("buy1", 11); Check(buyer.resourceGrants.Count == 1 && buyer.gold == 480, "Impossible delivery amount rejected");
        Ack("buy1", 0); Ack("buy1", 0);
        Check(buyer.gold == 500 && buyer.resourceGrants.Count == 0, "Full inventory refunded once");
        Buy("Flint", "partial"); Ack("partial", 2);
        Check(buyer.gold == 490 && buyer.resourceGrants.Count == 0, "Partial delivery refunds exact undelivered resource price");
        Buy("DeerHide", "complete"); Ack("complete", 5);
        Check(buyer.gold == 430 && buyer.resourceGrants.Count == 0, "Successful resource delivery charges exact pack price");
        buyer.processed.Add("complete"); Buy("DeerHide", "complete");
        Check(buyer.gold == 430 && buyer.resourceGrants.Count == 0, "Processed purchase cannot be replayed");
        shop.Economy = false; Buy("Wood", "disabled"); Check(buyer.gold == 430, "Disabled economy blocks vendor purchase"); shop.Economy = true;
        buyer.gold = 1; Buy("Wood", "poor"); Check(buyer.gold == 1 && buyer.resourceGrants.Count == 0, "Insufficient gold cannot create delivery");
        buyer.gold = 100; Buy("Wood", "saved");
        shop.Data.caravan = new CaravanState { active = true, x = 15, y = 35, z = -20 };
        var savedShop = MMOJson.FromJson<WorldStore>(MMOJson.ToJson(shop.Data));
        Check(savedShop.players.Single().resourceGrants.Single().id == "saved" && savedShop.caravan.active && savedShop.caravan.z == -20, "Resource delivery and caravan location survive persistence");
        var oldStore = MMOJson.FromJson<WorldStore>("{\"players\":[{\"id\":\"old\",\"name\":\"Old\",\"gold\":77}],\"guilds\":[]}");
        Check(oldStore.caravan != null && oldStore.players.Single().resourceGrants != null && oldStore.players.Single().gold == 77, "Pre-caravan saves preserve balances and initialize new fields");
        Check(WandererCatalog.Offers.All(o => o.Amount > 0 && o.UnitPrice > 0) && WandererCatalog.Offers.Select(o => o.Prefab).Distinct().Count() == WandererCatalog.Offers.Length, "Catalog has unique resources with valid prices");
        var market = new GameService(null); var customer = market.Join("market", "Market", 1000, now);
        string MarketBuy(string item, string vendor, bool nearby = true) => market.Execute("market", new Command { action = "trade", target = item, id = Guid.NewGuid().ToString("N") }, now, nearby, vendor);
        MarketBuy("Honey", "equipment"); Check(customer.gold == 1000 && customer.resourceGrants.Count == 0, "Equipment merchant cannot sell food");
        MarketBuy("Hammer", "food"); Check(customer.gold == 1000 && customer.resourceGrants.Count == 0, "Food merchant cannot sell equipment");
        MarketBuy("Honey", "food", false); Check(customer.gold == 1000, "Village purchase requires proximity");
        MarketBuy("Honey", "food"); var foodDelivery = customer.resourceGrants.Single();
        Check(customer.gold == 970 && foodDelivery.amount == 5 && foodDelivery.prefab == "Honey", "Food purchase reserves the correct pack and price");
        market.Execute("market", new Command { action = "tradeAck", target = foodDelivery.id, amount = 0 }, now);
        Check(customer.gold == 1000 && customer.resourceGrants.Count == 0, "Failed food delivery refunds the full purchase");
        MarketBuy("ArmorLeatherChest", "equipment"); var armorDelivery = customer.resourceGrants.Single();
        Check(customer.gold == 890 && armorDelivery.amount == 1 && armorDelivery.prefab == "ArmorLeatherChest", "Armor purchase delivers one item at fixed price");
        market.Execute("market", new Command { action = "tradeAck", target = armorDelivery.id, amount = 1 }, now);
        Check(customer.gold == 890 && customer.resourceGrants.Count == 0, "Armor delivery settles without refund");
        var allOffers = WandererCatalog.Offers.Concat(VillageCatalog.Food).Concat(VillageCatalog.Equipment).ToArray();
        Check(allOffers.Select(o => o.Prefab).Distinct().Count() == allOffers.Length && allOffers.All(o => o.Amount > 0 && o.UnitPrice > 0), "All merchant items are unambiguous with valid prices");
        Check(VillageCatalog.Food.All(o => o.Shop == "food") && VillageCatalog.Equipment.All(o => o.Shop == "equipment"), "Village catalogs keep vendor roles separate");
        var parts = VillageLayout.Create();
        Check(parts.Count(p => p.prefab == "wood_floor") == 8 && parts.Count(p => p.prefab == "wood_roof_45") == 8, "Village provides two fully floored and roofed shops");
        Check(parts.All(p => Math.Abs(p.x) <= 10 && p.z >= -5 && p.z <= 7), "Village layout fits inside the terrain validation footprint");
        Check(!parts.Any(p => Math.Abs(p.x) < 4 && p.z < -4), "Southern entrance remains unobstructed");
        Check(!parts.Any(p => Math.Abs(p.x + 6) < 1 && Math.Abs(p.z + 1) < 1) && !parts.Any(p => Math.Abs(p.x - 6) < 1 && Math.Abs(p.z + 1) < 1), "Both vendor standing areas remain clear");
        market.Data.village = new CaravanState { active = true, x = 30, y = 42, z = 50 };
        var restoredMarket = MMOJson.FromJson<WorldStore>(MMOJson.ToJson(market.Data));
        Check(restoredMarket.village.active && restoredMarket.village.x == 30 && restoredMarket.players.Single().gold == 890, "Village position and balances survive a restart");
        Check(oldStore.village != null && !oldStore.village.active, "Older saves initialize a new village without altering existing data");
        var manifest = System.IO.File.ReadAllText(System.IO.Path.Combine(Environment.GetEnvironmentVariable("ValheimDir") ?? throw new InvalidOperationException("Set ValheimDir to the Valheim installation directory."), "Valheim_Data", "StreamingAssets", "SoftRef", "manifest_extended"));
        var assetNames = System.Text.RegularExpressions.Regex.Matches(manifest, @"/([^/\r\n]+)\.prefab").Select(m => m.Groups[1].Value).ToHashSet();
        var missingParts = parts.Select(p => p.prefab).Distinct().Where(n => !assetNames.Contains(n)).ToArray();
        Check(missingParts.Length == 0, "Every village building prefab exists in the installed game: " + string.Join(", ", missingParts));
        var missingOffers = allOffers.Where(o => !assetNames.Contains(o.Prefab)).Select(o => o.Prefab).ToArray();
        Check(missingOffers.Length == 0, "Every merchant item prefab exists in the installed game: " + string.Join(", ", missingOffers));
        Check(assetNames.Contains("Dverger") && assetNames.Contains("DvergerMage"), "Both caravan NPC templates exist in the installed game");
        var planned = new CaravanState { planned = true, active = false, placementVersion = 1, x = 1800, y = 40, z = -2100 };
        var plannedAgain = MMOJson.FromJson<CaravanState>(MMOJson.ToJson(planned));
        Check(plannedAgain.planned && !plannedAgain.active && plannedAgain.placementVersion == 1 && plannedAgain.x == 1800, "Remote destination survives restart before its zone is loaded");
        Check(MMOJson.FromJson<CaravanState>("{\"active\":true,\"x\":30}").placementVersion == 0, "Legacy positions remain identifiable for one-time relocation");
        var sourceText = ModText.Catalog("Italian");
        foreach (var language in System.IO.File.ReadAllText("assets/localization/game-languages.txt").Trim().Split(',').Where(s => s.Length > 0 && s != "Abenaki"))
        {
            var translated = ModText.Catalog(language);
            Check(sourceText.Count > 250 && sourceText.Keys.All(k => translated.ContainsKey(k) && !string.IsNullOrWhiteSpace(translated[k])), language + " catalog covers every source text");
            Check(sourceText.All(pair => string.Join(",", System.Text.RegularExpressions.Regex.Matches(pair.Key, @"\{\d+\}").Select(m => m.Value).OrderBy(s => s)) == string.Join(",", System.Text.RegularExpressions.Regex.Matches(translated[pair.Key], @"\{\d+\}").Select(m => m.Value).OrderBy(s => s))), language + " preserves dynamic values");
        }
        Check(ModText.Translate("English", "Guida MMO MOD") == "MMO MOD Guide" && ModText.Translate("Italian", "Guida MMO MOD") == "Guida MMO MOD", "Language switching does not retain previous translations");
        Check(ModText.Translate("Abenaki", "Guida MMO MOD") == "MMO MOD Guide", "Unavailable language has explicit English fallback");
        const string literalName = "Gilda {0} $item_coins";
        Check(ModText.Resolve("English", ModText.Pack("Inviato a {0}", literalName)) == "Sent to " + literalName, "Player names are never translated or interpreted as formatting");
        Check(ModText.Resolve("English", "Inviato a " + literalName) == "Sent to " + literalName, "Legacy ledger preserves names");
        Check(ModText.Resolve("English", ModText.Pack("{0}: {1}", ModText.Term("Capogilda"), literalName)) == "Guild leader: " + literalName, "Only explicit terms are translated inside server messages");
        Check(ModText.Resolve("English", ModText.Pack("Ricevuti {0} {1}.", 5, ModText.Item("Wood")), p => p == "Wood" ? "NATIVE WOOD" : p).Contains("5 NATIVE WOOD"), "Items use the receiving client's native item translation");
        Check(ModText.Resolve("English", "@MMO_TEXT:null") == ModText.Translate("English", "Messaggio non disponibile."), "Malformed message cannot crash localization");
        Console.WriteLine("All " + checks + " behavioral checks passed.");
    }
}
